function hp = hiddenprop()

hp = {...
        'setnumber',...
        'setidentification'...
        'title',...
        'description',...
        'comment',...
        'free2shear',...
        'modified',...
        'modified by'
     };
 
 