function [p, q, u] = property()
persistent prop
if (isempty(prop) == 1)
    cpath = getcurrentdir();
    fileID = fopen([cpath '\parameters.csv']);
    if (fileID ~= -1)
        file = textscan(fileID,'%s','delimiter','\n');
        fclose(fileID);
        prop = {};
        for i=1:length(file{1})
            lin = textscan(file{1}{i},'%s','delimiter',',');
            prop{i,1} = lin{1}{1};
            if (length(lin{1}) == 2)
                prop{i,2} = lin{1}{2};
            else
                prop{i,2} = '';
            end %if
        end %i
        prop{i+1,1} = 'Reference';
        prop{i+1,2} = 'Qualitative';
        disp('Reading parameters list from "parameters.csv"...')
    else
        disp('"parameters.csv" NOT found, Using default parameters list...')
        prop = {...
                'Particle Size',           'µm';...
                'Relative Humidity',       '%';...
                'Detachment Fraction',     '';...
                'Resuspension Rate',       '1/s';...
                'Free Stream Velocity',    'm/s';...
                'Shear Velocity',          'm/s';...
                'Particle Reynolds',       '';... 
                'Threshold Velocity',      'm/s';...
                'Flow Acceleration',       'm/s^2';...
                'Turbulence Intensity',    '';...
                'Substrate Roughness(n)',  'µm';...
                'Dust Loading',            'g/m^2';...
                'Time',                    's';...
                'Pull Off Force',          'µN';...
                'Temperature',             '°C';...
                
                'Particle Material',       'Qualitative';...
                'Particle Shape',          'Qualitative';...
                'Substrate Material',      'Qualitative';...
                'Substrate Roughness',     'Qualitative';...
                'Deposit Structure',       'Qualitative';...
                'Particle Dispersion',     'Qualitative';...
                'Substrate Dimension',     'Qualitative';...
                'Wind Tunnel Dimension',   'Qualitative';...
                
                'Reference',               'Qualitative'...
                };
    end %if
    disp({'<<Parameter>>','<<Unit>>'})
    disp(prop)
end %if

p = {};
q = [];
u = {};
for i=1:size(prop,1)
    p{i} = prop{i,1};
    if strcmpi(prop{i,2},'Qualitative') == 1
        q(i) = 0;
        u{i} = '';
    else
        q(i) = 1;
        u{i} = prop{i,2};
    end %if
end %i

